name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the app.ja
      run: mvn clean package -DskipTests

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-application-jar
        path: target/application-0.0.1-SNAPSHOT.jar
