name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the app.jar
        run: mvn clean package -DskipTests

#      - name: Upload JAR file as artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: my-application-jar
#          path: target/application-0.0.1-SNAPSHOT.jar
            
      # Step 4: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Use GitHub username (will automatically resolve)
          password: ${{ secrets.GHCR_TOKEN }}  # Use the secret GitHub token

      # Step 5: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository.split('/')[1] }}/gus-chess:latest .

      # Step 6: Push the Docker image to GitHub Container Registry
      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository.split('/')[1] }}/gus-chess:latest